# Plex - Media Server
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-DVCYFytdfos9spEwUrrt
    volumes:
      - /home/jellyfin/torrents/downloads/docker:/config
      - /home/jellyfin/torrents/downloads/completed:/movies
    restart: unless-stopped
